version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user-music
      POSTGRES_PASSWORD: pass-music
      POSTGRES_DB: db-music

    ports:
      - "5433:5432"

    volumes:
      - music_data:/var/lib/postgresql/data

volumes:
  music_data:
    driver: local
