version: '3.8'

services:
  db:
    container_name: pg_db
    image: postgres:alpine
    restart: unless-stopped
    env_file:
    - ../.env
    ports:
      - "5433:5432"
    volumes:
      - music_data:/var/lib/postgresql/data

volumes:
  music_data:
    driver: local