version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: db-music
    env_file:
      - ../.env

    ports:
      - "5433:5432"

    volumes:
      - music_data:/var/lib/postgresql/data

volumes:
  music_data:
    driver: local
